<?php
namespace Backend\Controller;
class AppController extends InitController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if ( isset($_SESSION['uid']) ){
            if ($_SESSION['uid']==1 or $_SESSION['uid']==2){
                $this->assign('isadmin',1);
            }
        } else {
            $this->error('Your session timed out, now redirecting to login...','/auth/login',3);exit;
        }$this->assign('uid',session("uid"));
    }

    public function view()
    {
        $this->assign('SideBar_Selected','SideBar_ViewApp');
        $this->meta_title = L('SideBar_ViewApp');
        $this->display();
    }

    public function create()
    {
        $this->assign('user_gateways_info',M('gateways')->where(array("uid"=>session('uid')))->select());
        $this->assign('public_gateways_info',M('gateways')->where(array("access"=>"PUBLIC"))->where("`uid` !=".session('uid'))->select());
        $this->assign('SideBar_Selected','SideBar_CreateApp');
        $this->meta_title = L('SideBar_CreateApp');
        $this->display();
    }

    public function data()
    {
        $this->assign('SideBar_Selected','SideBar_AppData');
        $this->meta_title = L('SideBar_AppData');
        $this->display();
    }

    public function order()
    {
        $this->assign('SideBar_Selected','SideBar_OrderRetrieval');
        $this->meta_title = L('SideBar_OrderRetrieval');
        $this->display();
    }

}