<?php
namespace Api\Controller;

class OrderController extends InitController {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function generateOrder()
    {
        $appid = I('post.appid');
    }
}