<?php
namespace Frontend\Controller;
class AppController extends InitController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if ( isset($_SESSION['uid']) ){
            if ($_SESSION['uid']==1 or $_SESSION['uid']==2){
                $this->assign('isadmin',1);
            }
        } else {
            $this->error('Your session timed out, now redirecting to login...','/auth/login',3);exit;
        }$this->assign('uid',session("uid"));
    }

    public function view()
    {
        $this->meta_title = 'Applications View';
        $this->display();
    }
}